<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="calcTravelTime" Id="{55fc3503-48a6-4b54-aaa0-4cfced1a0548}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION calcTravelTime : INT
VAR_INPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="calcTravelTime">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>